### ISSUE TITLE
font-src rule

### ISSUE THREAD

**Issue by eLysgaard** [dixahq/elevio-client-packages#1]
We're using Elevio installed via NPM in our React project. We're having trouble figuring out how to load the fonts your library uses. From what we understand we would have to add `data:` to `font-src` of our content security policy. We would very much like to avoid having `data:` in our CSP, but we can't find any workarounds to this. 

Currently we've left it out of our CSP and our console looks like this when Elevio opens.
![image](https://user-images.githubusercontent.com/2428345/86592885-8a06fc00-bf94-11ea-921d-4eed4989a3e8.png)

Is it possible to configure the client so it doesn't try to load the fonts, or would we be able to provide them ourselves? Any workaround would be appreciated.

**Comment by kristian-puccio** [comment]
Hi @eLysgaard ,
Replied via our support email but just for reference here it is again.

​Those inline fonts have now been moved to our cdn.
​So if you change the font-src directive to include "*.elev.io" you will no longer see the CSP error.
​
Thanks,
Kristian
