### ISSUE TITLE
When I install and try to use it I am getting window is not defined

### ISSUE THREAD

**Issue by aleksandarcrvc** [dixahq/elevio-client-packages#11]
When I try to install elevio using npm it gives me window is not defined error. I am using this guide https://api-docs.elevio.help/en/articles/89-how-to-install-elevio-via-npm
Embeding script on index.html is working properly

Node version 15.14.0

**Comment by noccer** [comment]
Hi @aleksandarcrvc thanks for reaching out to us.

It sounds like you're having a server-side rendering issue. 

Today I spun up a brand new Create React App and it worked fine for me on Node v15.4.0.  I then spun up a brand new NextJS app and I got the same message you are seeing.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/18574446/169180945-0cc19de1-dcea-4799-917f-cb75b18be860.png">

While the elevio package does not support SSR yet, there are ways you can work around this issue using some defensive coding, until such time as we support SSR (not sure if it's in our roadmap or not). 

I got it working today in NextJS, here is what my `pages/index.tsx` file looked like to get Elevio working on the home page. In particular take a look at the useEffect at the top of the `Home` function.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/18574446/169183908-f067dfa6-b24f-4ac1-80a5-d68562df6a2c.png">


```javascript
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useEffect } from "react";

const Home: NextPage = () => {
  useEffect(() => {
    if (typeof window !== "undefined") {
      const Elevio = require("elevio").client;
      Elevio.load("YOUR_ACCOUNT_ID")
        .then(() => {
          console.log("Elevio has loaded, ready to use!");
        })
        .catch((error: any) => {
          console.error("Elevio failed to load", error);
        });
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

```

**Comment by aleksandarcrvc** [comment]
Yes you are right we are using Nuxt.js. Thanks for answer we can close this issue now and I will try your approach

**Comment by aleksandarcrvc** [comment]
Just for note when I tried this approach on Nuxt.js I am getting error
`in ./node_modules/elevio/esm/react.js
Module not found: Error: Can't resolve 'react' in '/app/node_modules/elevio/esm'`

**Comment by noccer** [comment]
Hey @aleksandarcrvc ,

Without a reproduction of the issue it will be hard for us to debug the above issue. In the Dixa knowledge team (formerly Elevio) we work exclusively with React, so we do not have much experience with Nuxt.js and vue.js. 

If you'd like us to see if we can find a solution to the issue, would you mind setting up a sample Nuxt.js repo that reproduces the above issue?

Our `elevio` module uses React under the hood, but this should not affect your Nuxt.js app. Perhaps Nuxt.js is stripping out packages that are not rendered on the client i.e. Perhaps it is stripping out `react` when it's rendering on the server because it can tell that `elevio` is not being run on the server side. I'm not sure how Nuxt.js does it's bundling.

I'd need to understand more about Nuxt.js and in particular this issue in order to help you proceed 🙂

Thanks.
