### ISSUE TITLE
`window is not defined` error when used in Next.js app router

### ISSUE THREAD

**Issue by cduff** [dixahq/elevio-client-packages#15]
Please see reproduction here:

https://codesandbox.io/p/sandbox/elevio-next-window-not-defined-kht2jz

**Comment by cduff** [comment]
I'm currently working around this using:

``` tsx
// Elevio.tsx
"use client";

import { react as ElevioReact } from "elevio";
import { ComponentPropsWithoutRef } from "react";

export default function Elevio(
  props: ComponentPropsWithoutRef<typeof ElevioReact>
) {
  return <ElevioReact {...props} />;
}

```

``` tsx
// Help.tsx
import dynamic from "next/dynamic";

// TODO: Works around elevio issue https://github.com/dixahq/elevio-client-packages/issues/15
const Elevio = dynamic(() => import("./Elevio"), { ssr: false });

export default function Help() {
  return <Elevio accountId="<account id>" />;
}
```

``` tsx
// layout.tsx
...
<body>
  ...
  <Help />
</body>
...
```

**Comment by cduff** [comment]
Similar problem if I try to use a `client` function in a component, e.g.

``` tsx
// SomeComponent.tsx
"use client";

import { client as elevio } from "elevio";

...
onClick={() => {
  elevio.openModule(id);
}}
...
```

Having to work around like:

``` tsx
// SomeComponent.tsx

"use client";
...
onClick={async () => {
  const elevio = (await import("elevio")).client;
  elevio.openModule(id);
}}
...
```

**Comment by kristian-puccio** [comment]
Cool thanks for the reproduction, I'll look into this for you

**Comment by kristian-puccio** [comment]
Fixed in 1.3.5 and improved in 1.3.6 (I quieted the warnings).

**Comment by cduff** [comment]
Thanks @kristian-puccio! Looking good.

Another improvement would be for the elevio react component to specify `"use client"` as per https://nextjs.org/docs/getting-started/react-essentials#third-party-packages.

I've created a reproduction for this requirement here: https://codesandbox.io/p/sandbox/elevio-next-window-not-defined-kht2jz.

**Comment by kristian-puccio** [comment]
Yep good call, done in 1.3.7
