### ISSUE TITLE
Missing release tag for 1.0.2

### ISSUE THREAD

**Issue by eLysgaard** [dixahq/elevio-client-packages#2]
Our dependency bot made a new PR that bumps our `elevio` npm package to `1.0.2`, but i can't find what changes are included. Could you please point me in the right direction?

Thanks!

**Comment by ssnielsen** [comment]
@kristian-puccio Saw that you've been the most active contributor to this. Do you have some insights into @eLysgaard's question?

**Comment by kristian-puccio** [comment]
Sorry about the delay! Life has been busy.
I've published the release notes here https://github.com/elevio/client-packages/releases/tag/1.0.2
Thanks!
