### ISSUE TITLE
Option "cspInlineScriptNonce" missing in TypeScript definition

### ISSUE THREAD

**Issue by codegain** [dixahq/elevio-client-packages#20]
Hi,

The setting `cspInlineScriptNonce` is missing in `elevio.ts` but should be available according to the documentation https://api-docs.elevio.help/en/articles/41

https://github.com/dixahq/elevio-client-packages/blob/master/src/elevio.ts#L179

**Comment by kristian-puccio** [comment]
Heya @codegain this is now fixed in version 1.3.8

Thanks for reporting!
