### ISSUE TITLE
React component does not expose all events

### ISSUE THREAD

**Issue by cduff** [dixahq/elevio-client-packages#5]
The React component exposes events like `onWidgetOpened` as documented here: https://api-docs.elevio.help/en/articles/90-how-to-integrate-elevio-into-react

However it only exposes a subset of the available underlying JavaScript API events as documented here: https://api-docs.elevio.help/en/articles/26

For example, in React there is no `onSuggestionsArticleClicked`.

It would be good if all the events were also available via the React component.

**Comment by kristian-puccio** [comment]
Hi @cduff,
good pick up. I'll add the missing events and push up a new version of the package. probably in the next day or two.

Cheers

**Comment by kristian-puccio** [comment]
Hi @cduff I've just pushed v1.2.0 which adds all the missing events https://github.com/dixahq/elevio-client-packages/releases/tag/v1.2.0

I don't have time at the moment to fill in the JSDoc but you can find the documentation on the KB page you listed above.

Let me know if you have any issue with it.
