### ISSUE TITLE
Unable to use package in Angular 12+

### ISSUE THREAD

**Issue by jtestarkey** [dixahq/elevio-client-packages#6]
When importing into an Angular 12 project, errors occur using either method of importing:

Using `import { client as Elevio } from 'elevio';`:
`Cannot find module 'react' or its corresponding type declarations.`

Using `import Elevio from 'elevio/lib/client';`
`Module not found: Error: Package path ./lib/client is not exported from package`

See stackblitz: https://stackblitz.com/edit/angular-efrvvu

Using any version previous to 12, these errors do not occur.

**Comment by kristian-puccio** [comment]
Hi @jtestarkey I'll just take a look into that now for you. I don't have any experience with Angular since versions 1.x so I'll have to do some digging :)

I wonder if they switched to using one of the new build tools? like Vite or Esbuild?

**Comment by kristian-puccio** [comment]
Oh and thanks for the Stackblitz, very helpful!

**Comment by kristian-puccio** [comment]
@jtestarkey if you change the import from 
`import Elevio from 'elevio/lib/client';` to `import Elevio from 'elevio/esm/client';` then it works fine.

Let me know if you still have issues.

**Comment by jtestarkey** [comment]
Thanks for looking into this so quickly @kristian-puccio, unfortunately I'm still not having any luck although it seems to work in stackblitz.
The error I get now is:
```
Error: Module not found: Error: Package path ./esm/client is not exported from package node_modules\elevio (see exports field in node_modules\elevio\package.json)
```

Do you have any other ideas?

**Comment by utlime** [comment]
Hi @kristian-puccio ,
I have the same problem when I'm trying to use 
`import Elevio from 'elevio/esm/client';`

We don't use react so I can not import index file. So we have to use 1.0.3

**Comment by kristian-puccio** [comment]
Oh sorry about that.

I'll try removing the React file from the index and looking at the exports map to see if I can fix this.

**Comment by kristian-puccio** [comment]
@jtestarkey do you mind sharing how to setup an Angular app or point me in the right direction?
I haven't used Angular since version 1 and I believe quite a lot has changed!

**Comment by jtestarkey** [comment]
@kristian-puccio I've created a quick sample app here, let me know if you have any questions:
https://github.com/jtestarkey/elevio-angular

**Comment by kristian-puccio** [comment]
@jtestarkey thanks for that, I can now replicate the issue, I'll let you know when I've fixed it

**Comment by kristian-puccio** [comment]
@jtestarkey this should be fixed with this release https://github.com/dixahq/elevio-client-packages/releases/tag/v1.3.0
Re-open the ticket if you have any issues with it.

Cheers
