### ISSUE TITLE
Article/Module/Category IDs incorrectly typed as strings for events

### ISSUE THREAD

**Issue by cduff** [dixahq/elevio-client-packages#7]
In various events the values of article/module/category IDs are passed. These are always integer IDs and the actual values at runtime are `number` type as expected. However they are typed as `string` in TypeScript which is incorrect.

For example:

``` TypeScript
  'module:opened': (moduleId: string) => void;
```

**Comment by kristian-puccio** [comment]
Hi @cduff sorry about the delay getting back to you, been on summer break.

I know... the issue is that the under lying code that this npm module calls is written pre Typescript the id's should all be string but sometimes internally we use a number.

I could change all the types to be number|string if that helps.
I don't think I could get them all to be perfectly correct as sometimes triggering events in different ways can lead in some situations for a number to be output and other times a string.

Let me know what you think.

**Comment by cduff** [comment]
Thanks for getting back to me on this @kristian-puccio. I hope you had a good break.

From my understanding of Elevio, the Articles, Modules and Categories are all allocated integer ID values which auto-increment within the scope of an account. If that's correct, wouldn't it make the most sense for these values to be typed as `number` and to ensure they're `number` values at runtime (I've only seen them as `number` at runtime in my testing so far)?

To work around this, currently I'm wrapping all the following event parameters in `parseInt` function calls:

- module:opened - moduleId
- category:article:clicked - articleId, categoryId
- suggestions:article:clicked - articleId
- search:article:clicked - articleId
- related:article:clicked - articleId, relatedFrom
- article:interlink:clicked - id, clickedFrom
- helper:clicked - actionId
- widget:article:view - articleId

Changing the types to `number | string` would be more correct than the current clearly incorrect typings but still wouldn't be ideal from my understanding as it would still require manipulating into plain `number` values.

Thoughts?

**Comment by kristian-puccio** [comment]
@cduff I'm going through the events at the moment and doing my best to make the types as accurate as possible. shouldn't be too far off.
Unfortunately some types will be `string | number` but only a few

**Comment by cduff** [comment]
> @cduff I'm going through the events at the moment and doing my best to make the types as accurate as possible. shouldn't be too far off. Unfortunately some types will be `string | number` but only a few

Sounds good. Looking forward to checking out the changes when they come through.

**Comment by kristian-puccio** [comment]
@cduff just published v1.3.1 with the updated types.
One thing I did notice though is that the search events are missing the categoryId. The backend developer responsible for that code is on leave at the moment, so when he gets back and re-adds it I'll publish a new version of this package with categoryId added back in.

**Comment by cduff** [comment]
Thanks for your work on this @kristian-puccio!

I notice that the following parameters are still not `number`:

suggestions:article:clicked - articleId
related:article:clicked - articleId, relatedFrom
article:interlink:clicked - id, clickedFrom
helper:clicked - actionId
widget:article:view - articleId

Is there any reason for this?

**Comment by kristian-puccio** [comment]
@cduff it's unfortunately the result of having code with no types.
All our newer code is pure Typescript with api types generated.
We did start a re-write of this project but the acquisition by Dixa has put that plan on hold.

Sorry about the inconsistencies!
