### ISSUE TITLE
NextJS support

### ISSUE THREAD

**Issue by jackpordi** [dixahq/elevio-client-packages#9]
As per #3 , this SDK doesn't work in NextJS at the moment. This is because the `window` object is not available in Next's initial server/static rendering phase.

Particularly, `window` is available in `useEffect` calls in React, but not elsewhere - like is being used in these two places at the moment:

https://github.com/dixahq/elevio-client-packages/blob/9a578a778effe6f1f98a2de59e59b20fcf23828a/src/client.ts#L9

https://github.com/dixahq/elevio-client-packages/blob/9a578a778effe6f1f98a2de59e59b20fcf23828a/src/client.ts#L163

**Comment by jackpordi** [comment]
An easy fix for line 9 is just changing adding an additional condition: `if (typeof window !== "undefined")` but I'm not sure about the one on 163.

**Comment by nicolaiberghan** [comment]
@jackel119 looking into this one now

**Comment by nicolaiberghan** [comment]
@jackel119 I've added PR. Does this fix your issue?

**Comment by jackpordi** [comment]
Yes, that works for me, though you might want to do

```js
if (typeof window !== "undefined" $$ !window._elev)
```

on line 9 instead.
